#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = configPkg
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
D:/ti/xdctools_3_50_04_43_core/packages/xdc/utils.js:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/utils.js
D:/ti/xdctools_3_50_04_43_core/packages/xdc/xdc.tci:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/xdc.tci
D:/ti/xdctools_3_50_04_43_core/packages/xdc/template.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/template.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/om2.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/om2.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/xmlgen.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/xmlgen.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/xmlgen2.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/xmlgen2.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/Warnings.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/Warnings.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/IPackage.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/IPackage.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/package.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/package.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/services/global/Clock.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/services/global/Clock.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/services/global/Trace.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/services/global/Trace.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/bld.js:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/bld.js
D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/BuildEnvironment.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/PackageContents.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/PackageContents.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/_gen.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/_gen.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/Library.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/Library.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/Executable.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/Executable.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/Repository.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/Repository.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/Configuration.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/Configuration.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/Script.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/Script.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/Manifest.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/Manifest.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/Utils.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/Utils.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/ITarget.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/ITarget.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/ITarget2.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/ITarget2.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/ITarget3.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/ITarget3.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/ITargetFilter.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/package.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/bld/package.xs
package.mak: config.bld
D:/ti/bios_6_53_02_00/packages/ti/targets/ITarget.xs:
package.mak: D:/ti/bios_6_53_02_00/packages/ti/targets/ITarget.xs
D:/ti/bios_6_53_02_00/packages/ti/targets/C28_large.xs:
package.mak: D:/ti/bios_6_53_02_00/packages/ti/targets/C28_large.xs
D:/ti/bios_6_53_02_00/packages/ti/targets/C28_float.xs:
package.mak: D:/ti/bios_6_53_02_00/packages/ti/targets/C28_float.xs
D:/ti/bios_6_53_02_00/packages/ti/targets/package.xs:
package.mak: D:/ti/bios_6_53_02_00/packages/ti/targets/package.xs
D:/ti/bios_6_53_02_00/packages/ti/targets/arm/elf/IArm.xs:
package.mak: D:/ti/bios_6_53_02_00/packages/ti/targets/arm/elf/IArm.xs
D:/ti/bios_6_53_02_00/packages/ti/targets/arm/elf/package.xs:
package.mak: D:/ti/bios_6_53_02_00/packages/ti/targets/arm/elf/package.xs
package.mak: package.bld
D:/ti/xdctools_3_50_04_43_core/packages/xdc/tools/configuro/template/compiler.opt.xdt:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/tools/configuro/template/compiler.opt.xdt
D:/ti/xdctools_3_50_04_43_core/packages/xdc/services/io/File.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/services/io/File.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/services/io/package.xs:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/services/io/package.xs
D:/ti/xdctools_3_50_04_43_core/packages/xdc/tools/configuro/template/compiler.defs.xdt:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/tools/configuro/template/compiler.defs.xdt
D:/ti/xdctools_3_50_04_43_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/tools/configuro/template/custom.mak.exe.xdt
D:/ti/xdctools_3_50_04_43_core/packages/xdc/tools/configuro/template/package.xs.xdt:
package.mak: D:/ti/xdctools_3_50_04_43_core/packages/xdc/tools/configuro/template/package.xs.xdt
endif

ti.targets.arm.elf.R4F.rootDir ?= D:/ti/ti-cgt-arm_16.9.6.LTS
ti.targets.arm.elf.packageBase ?= D:/ti/bios_6_53_02_00/packages/ti/targets/arm/elf/
.PRECIOUS: $(XDCCFGDIR)/%.oer4f
.PHONY: all,er4f .dlls,er4f .executables,er4f test,er4f
all,er4f: .executables,er4f
.executables,er4f: .libraries,er4f
.executables,er4f: .dlls,er4f
.dlls,er4f: .libraries,er4f
.libraries,er4f: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,er4f
	@$(ECHO) xdc .executables,er4f
	@$(ECHO) xdc .libraries,er4f
	@$(ECHO) xdc .dlls,er4f


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_configPkg.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package configPkg" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.dlls,er4f .dlls: mmw.per4f

-include package/cfg/mmw_per4f.mak
-include package/cfg/mmw_per4f.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/mmw_per4f.dep
endif
mmw.per4f: package/cfg/mmw_per4f.xdl
	@


ifeq (,$(wildcard .libraries,er4f))
mmw.per4f package/cfg/mmw_per4f.c: .libraries,er4f
endif

package/cfg/mmw_per4f.c package/cfg/mmw_per4f.h package/cfg/mmw_per4f.xdl: override _PROG_NAME := mmw.xer4f
package/cfg/mmw_per4f.c: package/cfg/mmw_per4f.cfg
package/cfg/mmw_per4f.xdc.inc: package/cfg/mmw_per4f.xdl
package/cfg/mmw_per4f.xdl package/cfg/mmw_per4f.c: .interfaces

clean:: clean,er4f
	-$(RM) package/cfg/mmw_per4f.cfg
	-$(RM) package/cfg/mmw_per4f.dep
	-$(RM) package/cfg/mmw_per4f.c
	-$(RM) package/cfg/mmw_per4f.xdc.inc

clean,er4f::
	-$(RM) mmw.per4f
.executables,er4f .executables: mmw.xer4f

mmw.xer4f: |mmw.per4f

-include package/cfg/mmw.xer4f.mak
mmw.xer4f: package/cfg/mmw_per4f.oer4f 
	$(RM) $@
	@$(MSG) lnker4f $@ ...
	$(RM) $(XDCCFGDIR)/$@.map
	$(ti.targets.arm.elf.R4F.rootDir)/bin/armlnk -fs $(XDCCFGDIR)$(dir $@). -q -u _c_int00 --silicon_version=7R4 --strict_compatibility=on  -o $@ package/cfg/mmw_per4f.oer4f   package/cfg/mmw_per4f.xdl  -w -c -m $(XDCCFGDIR)/$@.map -l $(ti.targets.arm.elf.R4F.rootDir)/lib/libc.a
	
mmw.xer4f: export C_DIR=
mmw.xer4f: PATH:=$(ti.targets.arm.elf.R4F.rootDir)/bin/;$(PATH)
mmw.xer4f: Path:=$(ti.targets.arm.elf.R4F.rootDir)/bin/;$(PATH)

mmw.test test,er4f test: mmw.xer4f.test

mmw.xer4f.test:: mmw.xer4f
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 mmw.xer4f.test
else
	@$(MSG) running $<  ...
	$(call EXEC.mmw.xer4f, ) 
endif

clean,er4f::
	-$(RM) $(wildcard .tmp,mmw.xer4f,*)


clean:: clean,er4f

clean,er4f::
	-$(RM) mmw.xer4f
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
mmw_per4f.oer4f,copy : package/cfg/mmw_per4f.oer4f
mmw_per4f.ser4f,copy : package/cfg/mmw_per4f.ser4f

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,configPkg
ifeq (,$(MK_NOGENDEPS))
-include package/rel/configPkg.tar.dep
endif
package/rel/configPkg/configPkg/package/package.rel.xml: package/package.bld.xml
package/rel/configPkg/configPkg/package/package.rel.xml: package/build.cfg
package/rel/configPkg/configPkg/package/package.rel.xml: package/package.xdc.inc
package/rel/configPkg/configPkg/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

configPkg.tar: package/rel/configPkg.xdc.inc package/rel/configPkg/configPkg/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/configPkg.xdc.inc,package/rel/configPkg.tar.dep)


release release,configPkg: all configPkg.tar
clean:: .clean
	-$(RM) configPkg.tar
	-$(RM) package/rel/configPkg.xdc.inc
	-$(RM) package/rel/configPkg.tar.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package

include custom.mak
